processors:
  -
    dll: D:\Work\myProcessorAgent\ElasticProcessor\bin\Debug\net6.0\ElasticProcessor.dll
    config: D:\Work\myProcessorAgent\SuperAgent\config\processor-elastic.yaml
    name: Elasticsearch writer1
  -
    dll: D:\Work\myProcessorAgent\ElasticProcessor\bin\Debug\net6.0\ElasticProcessor.dll
    config: D:\Work\myProcessorAgent\SuperAgent\config\processor-elastic.yaml
    name: Elasticsearch writer2
  -
    dll: D:\Work\myProcessorAgent\ElasticProcessor\bin\Debug\net6.0\ElasticProcessor.dll
    config: D:\Work\myProcessorAgent\SuperAgent\config\processor-elastic.yaml
    name: Elasticsearch writer3
connectors:
  -
    destination: Elasticsearch writer1
    input: kafka
    inputConfig: D:\Work\myProcessorAgent\SuperAgent\config\input-kafka.yaml
    output: kafka
    outputConfig: D:\Work\myProcessorAgent\SuperAgent\config\output-kafka.yaml